// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ervwhmtnmzgqasqlnrqr.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImVydndobXRubXpncWFzcWxucnFyIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTc2MDA3NDQsImV4cCI6MjA3MzE3Njc0NH0.VqdE9FN_VBZe6j2yaSgnIF4vkkodMOtQK4hBJ14Qr0g";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});